sudo: required
services: 
  - docker

before_install:
  - docker build -t rakeshpetit/docker-react -f Dockerfile.dev .

script:
  -docker run -e CI=true rakeshpetit/docker-react npm run test
  # -docker run -e CI=true rakeshpetit/docker-react npm run test -- --coverage