sudo: required
services: 
  - docker

before_install:
  - docker build -t rakeshpetit/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rakeshpetit/docker-react npm run test
  # -docker run -e CI=true rakeshpetit/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "$AWS_REGION"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "$AWS_BUCKET"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
      secure: "$AWS_SECRET_KEY"